### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by sayanarijit** [dnaeon/pyinfoblox#11]
Hi, I like this module. Please add a license so that we can use it and contribute on its development.

**Comment by dnaeon** [comment]
Hi,

The source file contains a license header and also setup.py indicates it as well.

I’ll add a separate LICENSE file after the holidays to make it clearer.

This project is licensed under the BSD license.

Contributions are welcome!

Thanks,
Marin

**Comment by dnaeon** [comment]
The readme also mentions the license, so closing this one.
