### ISSUE TITLE
Add Timeout option to the "requests" calls

### ISSUE THREAD

**Issue by racsoce** [dnaeon/pyinfoblox#8]
Is there a way to add the timeout parameter to change the default value (180) in the request calls?

I had to add this in the get Object to send the timeout parameter to the "requests" get:

    def get(self, objref=None, timeout=180, **kwargs):
        """
        Get Infoblox objects

        Returns:
            With objref, one Infoblox object,
            in search form, a list of Infoblox objects

        Raises:
            InfobloxWAPIException

        """
        r = self.session.get(
            self.wapi + (objref if objref is not None else self.objtype),
            params=kwargs, timeout=timeout
        )

**Comment by dnaeon** [comment]
Can you submit a PR for getting this one merged?

Thanks!

**Comment by racsoce** [comment]
Sure, Done:
https://github.com/dnaeon/pyinfoblox/pull/9

Thanks,
